# .streamlit/secrets.toml

[connections.gsheets]
spreadsheet = "13KuWaFEb1toVn4cZ6PZL2Wawc4QZZPjZ5bLP70wih4A"
type = "service_account"
project_id = "welder-admin"
private_key_id = "5309464a6844a0e4a5c89920d342bdc3b88cf795"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC7YwFzA/oMmDlM...\n-----END PRIVATE KEY-----\n"
client_email = "welder-admin@welder-admin.iam.gserviceaccount.com"
client_id = "103555416971526973052"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/welder-admin%40welder-admin.iam.gserviceaccount.com"
